### ISSUE TITLE
Bug Fixes for #28 PR

### ISSUE THREAD

**Issue by manjushsh** [manjushsh/file-encrypt-decrypt#31]
### TO-DO / BUGS NEED TO BE FIXED as of #28 :

- [x] Drag and drop in file decryption screen breaks app. Please choose a file by click and pick.
- [ ] Exported zip inconstancy fixes (In drag and drop and file selection)
- [ ] Bulk file decryption
- [ ] Decrypt from ZIP file
- [ ] Loader in between screens while screen change (Currently white splash screen is shown for few milliseconds)
